"""Build metadata for the running installation.

`_buildinfo.py` is generated by the release build (see `tools/build/make_buildinfo.py`)
and is intentionally absent from version control. When it is missing — a source
checkout or a development install — this module reports a clearly labelled
"development" build instead.
"""

from __future__ import annotations

import platform
from dataclasses import dataclass

import dentiva


@dataclass(frozen=True, slots=True)
class BuildInfo:
    version: str
    git_commit: str
    build_date: str
    python_version: str
    qt_version: str
    channel: str

    @property
    def is_release_build(self) -> bool:
        return self.channel == "release"

    def describe(self) -> str:
        return (
            f"Dentiva Pro {self.version} ({self.channel}) · "
            f"commit {self.git_commit} · built {self.build_date} · "
            f"Python {self.python_version} · Qt {self.qt_version}"
        )


def _qt_version() -> str:
    try:
        from PySide6 import __version__ as pyside_version
    except ImportError:  # pragma: no cover - only when Qt is unavailable
        return "unavailable"
    return str(pyside_version)


def load_build_info() -> BuildInfo:
    """Return build metadata, falling back to development defaults."""
    try:
        from dentiva._buildinfo import BUILD_INFO  # type: ignore[attr-defined]

        data = dict(BUILD_INFO)
    except ImportError:
        data = {}
    return BuildInfo(
        version=str(data.get("version", dentiva.__version__)),
        git_commit=str(data.get("git_commit", "source")),
        build_date=str(data.get("build_date", "development")),
        python_version=str(data.get("python_version", platform.python_version())),
        qt_version=str(data.get("qt_version", _qt_version())),
        channel=str(data.get("channel", "development")),
    )


BUILD = load_build_info()
